-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hilbert_envelope_axis_p_hls_fptosi_float_i32 is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of hilbert_envelope_axis_p_hls_fptosi_float_i32 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal data_fu_42_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_64_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_68_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_54_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_82_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_86_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_100_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_92_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_fu_106_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_110_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_1_fu_118_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_78_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_122_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_126_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_132_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_1_fu_138_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_148_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_158_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_fu_46_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_1_fu_166_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    add_ln317_fu_86_p2 <= std_logic_vector(unsigned(zext_ln317_fu_82_p1) + unsigned(ap_const_lv9_181));
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        result_1_fu_166_p2 when (xs_sign_fu_46_p3(0) = '1') else 
        val_fu_158_p3;
    data_fu_42_p1 <= x;
    lshr_ln18_fu_126_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_78_p1),to_integer(unsigned('0' & zext_ln18_fu_122_p1(31-1 downto 0)))));
    mantissa_fu_68_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_64_p1) & ap_const_lv1_0);
    result_1_fu_166_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_158_p3));
    select_ln18_fu_110_p3 <= 
        sext_ln18_fu_106_p1 when (tmp_fu_92_p3(0) = '1') else 
        add_ln317_fu_86_p2;
        sext_ln18_1_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_110_p3),32));

        sext_ln18_fu_106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_100_p2),9));

    shl_ln18_fu_132_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_78_p1),to_integer(unsigned('0' & zext_ln18_fu_122_p1(31-1 downto 0)))));
    sub_ln18_fu_100_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_54_p4));
    tmp_1_fu_138_p4 <= lshr_ln18_fu_126_p2(55 downto 24);
    tmp_2_fu_148_p4 <= shl_ln18_fu_132_p2(55 downto 24);
    tmp_fu_92_p3 <= add_ln317_fu_86_p2(8 downto 8);
    trunc_ln342_fu_64_p1 <= data_fu_42_p1(23 - 1 downto 0);
    val_fu_158_p3 <= 
        tmp_1_fu_138_p4 when (tmp_fu_92_p3(0) = '1') else 
        tmp_2_fu_148_p4;
    xs_exp_fu_54_p4 <= data_fu_42_p1(30 downto 23);
    xs_sign_fu_46_p3 <= data_fu_42_p1(31 downto 31);
    zext_ln15_fu_78_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_68_p4),79));
    zext_ln18_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_118_p1),79));
    zext_ln317_fu_82_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_54_p4),9));
end behav;
