// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module calculateCoefficients_calculateCoefficients_Pipeline_VITIS_LOOP_16_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        sext_ln16,
        div1,
        omegaUpper,
        omegaLower,
        grp_fu_134_p_din0,
        grp_fu_134_p_din1,
        grp_fu_134_p_opcode,
        grp_fu_134_p_dout0,
        grp_fu_134_p_ce,
        grp_fu_138_p_din0,
        grp_fu_138_p_dout0,
        grp_fu_138_p_ce,
        grp_fu_144_p_din0,
        grp_fu_144_p_dout0,
        grp_fu_144_p_ce,
        grp_fu_147_p_din0,
        grp_fu_147_p_din1,
        grp_fu_147_p_dout0,
        grp_fu_147_p_ce,
        grp_fu_157_p_din0,
        grp_fu_157_p_din1,
        grp_fu_157_p_dout0,
        grp_fu_157_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [61:0] sext_ln16;
input  [63:0] div1;
input  [31:0] omegaUpper;
input  [31:0] omegaLower;
output  [31:0] grp_fu_134_p_din0;
output  [31:0] grp_fu_134_p_din1;
output  [1:0] grp_fu_134_p_opcode;
input  [31:0] grp_fu_134_p_dout0;
output   grp_fu_134_p_ce;
output  [63:0] grp_fu_138_p_din0;
input  [31:0] grp_fu_138_p_dout0;
output   grp_fu_138_p_ce;
output  [31:0] grp_fu_144_p_din0;
input  [63:0] grp_fu_144_p_dout0;
output   grp_fu_144_p_ce;
output  [63:0] grp_fu_147_p_din0;
output  [63:0] grp_fu_147_p_din1;
input  [63:0] grp_fu_147_p_dout0;
output   grp_fu_147_p_ce;
output  [63:0] grp_fu_157_p_din0;
output  [63:0] grp_fu_157_p_din1;
input  [63:0] grp_fu_157_p_dout0;
output   grp_fu_157_p_ce;

reg ap_idle;
reg m_axi_gmem_WVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln16_fu_211_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire  signed [4:0] add_ln19_fu_188_p2;
reg  signed [4:0] add_ln19_reg_263;
reg  signed [4:0] add_ln19_reg_263_pp0_iter1_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter2_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter3_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter4_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter5_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter6_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter7_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter8_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter9_reg;
reg  signed [4:0] add_ln19_reg_263_pp0_iter10_reg;
wire   [0:0] icmp_ln19_fu_194_p2;
reg   [0:0] icmp_ln19_reg_268;
reg   [0:0] icmp_ln19_reg_268_pp0_iter1_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter2_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter3_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter4_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter5_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter6_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter7_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter8_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter9_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter10_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter11_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter12_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter13_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter14_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter15_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter16_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter17_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter18_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter19_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter20_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter21_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter22_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter23_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter24_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter25_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter26_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter27_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter28_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter29_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter30_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter31_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter32_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter33_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter34_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter35_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter36_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter37_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter38_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter39_reg;
reg   [0:0] icmp_ln19_reg_268_pp0_iter40_reg;
wire   [31:0] grp_fu_154_p1;
reg   [31:0] conv4_reg_281;
wire   [31:0] grp_fu_146_p2;
reg   [31:0] p_x_assign_reg_287;
wire   [31:0] grp_fu_150_p2;
reg   [31:0] p_x_assign_1_reg_292;
wire   [31:0] grp_sin_or_cos_float_s_fu_116_ap_return;
reg   [31:0] tmp_reg_302;
wire   [31:0] grp_sin_or_cos_float_s_fu_129_ap_return;
reg   [31:0] tmp_s_reg_307;
wire   [63:0] grp_fu_173_p1;
reg   [63:0] conv6_reg_312;
reg   [31:0] sub_reg_317;
reg   [63:0] conv5_reg_322;
reg   [63:0] mul3_reg_327;
reg   [31:0] storereflowmerge_reg_337;
reg    grp_sin_or_cos_float_s_fu_116_ap_ce;
reg    ap_block_pp0_stage0_11001_ignoreCallOp76;
reg    grp_sin_or_cos_float_s_fu_129_ap_ce;
reg    ap_block_pp0_stage0_11001_ignoreCallOp77;
wire   [63:0] ap_phi_reg_pp0_iter0_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter1_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter2_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter3_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter4_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter5_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter6_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter7_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter8_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter9_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter10_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter11_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter12_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter13_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter14_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter15_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter16_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter17_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter18_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter19_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter20_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter21_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter22_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter23_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter24_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter25_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter26_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter27_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter28_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter29_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter30_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter31_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter32_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter33_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter34_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter35_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter36_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter37_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter38_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter39_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter40_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter41_storereflowmerge_in_reg_106;
reg   [63:0] ap_phi_reg_pp0_iter42_storereflowmerge_in_reg_106;
wire    ap_block_pp0_stage0_ignoreCallOp76;
wire    ap_block_pp0_stage0_ignoreCallOp77;
wire    ap_block_pp0_stage0_01001;
reg   [4:0] i1_fu_70;
wire   [4:0] i_fu_200_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i1_load;
wire  signed [31:0] grp_fu_154_p0;
wire  signed [31:0] grp_fu_173_p0;
reg    grp_fu_142_ce;
reg    grp_fu_146_ce;
reg    grp_fu_150_ce;
reg    grp_fu_154_ce;
reg    grp_fu_157_ce;
reg    grp_fu_161_ce;
reg    grp_fu_164_ce;
reg    grp_fu_169_ce;
reg    grp_fu_173_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_block_pp0_stage0_00001;
reg    ap_condition_555;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 i1_fu_70 = 5'd0;
#0 ap_done_reg = 1'b0;
end

calculateCoefficients_sin_or_cos_float_s grp_sin_or_cos_float_s_fu_116(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t_in(p_x_assign_reg_287),
    .ap_return(grp_sin_or_cos_float_s_fu_116_ap_return),
    .ap_ce(grp_sin_or_cos_float_s_fu_116_ap_ce)
);

calculateCoefficients_sin_or_cos_float_s grp_sin_or_cos_float_s_fu_129(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t_in(p_x_assign_1_reg_292),
    .ap_return(grp_sin_or_cos_float_s_fu_129_ap_return),
    .ap_ce(grp_sin_or_cos_float_s_fu_129_ap_ce)
);

calculateCoefficients_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(omegaUpper),
    .din1(conv4_reg_281),
    .ce(grp_fu_146_ce),
    .dout(grp_fu_146_p2)
);

calculateCoefficients_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(omegaLower),
    .din1(conv4_reg_281),
    .ce(grp_fu_150_ce),
    .dout(grp_fu_150_p2)
);

calculateCoefficients_sitofp_32s_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32s_32_4_no_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_154_p0),
    .ce(grp_fu_154_ce),
    .dout(grp_fu_154_p1)
);

calculateCoefficients_sitodp_32s_64_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32s_64_4_no_dsp_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_173_p0),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p1)
);

calculateCoefficients_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter44_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter43_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter44_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_555)) begin
        if ((icmp_ln19_fu_194_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_storereflowmerge_in_reg_106 <= div1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter0_storereflowmerge_in_reg_106;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
        if ((icmp_ln19_reg_268_pp0_iter40_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter42_storereflowmerge_in_reg_106 <= grp_fu_157_p_dout0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter42_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter41_storereflowmerge_in_reg_106;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            i1_fu_70 <= i_fu_200_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i1_fu_70 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln19_reg_263 <= add_ln19_fu_188_p2;
        add_ln19_reg_263_pp0_iter1_reg <= add_ln19_reg_263;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln19_reg_268 <= icmp_ln19_fu_194_p2;
        icmp_ln19_reg_268_pp0_iter1_reg <= icmp_ln19_reg_268;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln19_reg_263_pp0_iter10_reg <= add_ln19_reg_263_pp0_iter9_reg;
        add_ln19_reg_263_pp0_iter2_reg <= add_ln19_reg_263_pp0_iter1_reg;
        add_ln19_reg_263_pp0_iter3_reg <= add_ln19_reg_263_pp0_iter2_reg;
        add_ln19_reg_263_pp0_iter4_reg <= add_ln19_reg_263_pp0_iter3_reg;
        add_ln19_reg_263_pp0_iter5_reg <= add_ln19_reg_263_pp0_iter4_reg;
        add_ln19_reg_263_pp0_iter6_reg <= add_ln19_reg_263_pp0_iter5_reg;
        add_ln19_reg_263_pp0_iter7_reg <= add_ln19_reg_263_pp0_iter6_reg;
        add_ln19_reg_263_pp0_iter8_reg <= add_ln19_reg_263_pp0_iter7_reg;
        add_ln19_reg_263_pp0_iter9_reg <= add_ln19_reg_263_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv4_reg_281 <= grp_fu_154_p1;
        conv5_reg_322 <= grp_fu_144_p_dout0;
        conv6_reg_312 <= grp_fu_173_p1;
        icmp_ln19_reg_268_pp0_iter10_reg <= icmp_ln19_reg_268_pp0_iter9_reg;
        icmp_ln19_reg_268_pp0_iter11_reg <= icmp_ln19_reg_268_pp0_iter10_reg;
        icmp_ln19_reg_268_pp0_iter12_reg <= icmp_ln19_reg_268_pp0_iter11_reg;
        icmp_ln19_reg_268_pp0_iter13_reg <= icmp_ln19_reg_268_pp0_iter12_reg;
        icmp_ln19_reg_268_pp0_iter14_reg <= icmp_ln19_reg_268_pp0_iter13_reg;
        icmp_ln19_reg_268_pp0_iter15_reg <= icmp_ln19_reg_268_pp0_iter14_reg;
        icmp_ln19_reg_268_pp0_iter16_reg <= icmp_ln19_reg_268_pp0_iter15_reg;
        icmp_ln19_reg_268_pp0_iter17_reg <= icmp_ln19_reg_268_pp0_iter16_reg;
        icmp_ln19_reg_268_pp0_iter18_reg <= icmp_ln19_reg_268_pp0_iter17_reg;
        icmp_ln19_reg_268_pp0_iter19_reg <= icmp_ln19_reg_268_pp0_iter18_reg;
        icmp_ln19_reg_268_pp0_iter20_reg <= icmp_ln19_reg_268_pp0_iter19_reg;
        icmp_ln19_reg_268_pp0_iter21_reg <= icmp_ln19_reg_268_pp0_iter20_reg;
        icmp_ln19_reg_268_pp0_iter22_reg <= icmp_ln19_reg_268_pp0_iter21_reg;
        icmp_ln19_reg_268_pp0_iter23_reg <= icmp_ln19_reg_268_pp0_iter22_reg;
        icmp_ln19_reg_268_pp0_iter24_reg <= icmp_ln19_reg_268_pp0_iter23_reg;
        icmp_ln19_reg_268_pp0_iter25_reg <= icmp_ln19_reg_268_pp0_iter24_reg;
        icmp_ln19_reg_268_pp0_iter26_reg <= icmp_ln19_reg_268_pp0_iter25_reg;
        icmp_ln19_reg_268_pp0_iter27_reg <= icmp_ln19_reg_268_pp0_iter26_reg;
        icmp_ln19_reg_268_pp0_iter28_reg <= icmp_ln19_reg_268_pp0_iter27_reg;
        icmp_ln19_reg_268_pp0_iter29_reg <= icmp_ln19_reg_268_pp0_iter28_reg;
        icmp_ln19_reg_268_pp0_iter2_reg <= icmp_ln19_reg_268_pp0_iter1_reg;
        icmp_ln19_reg_268_pp0_iter30_reg <= icmp_ln19_reg_268_pp0_iter29_reg;
        icmp_ln19_reg_268_pp0_iter31_reg <= icmp_ln19_reg_268_pp0_iter30_reg;
        icmp_ln19_reg_268_pp0_iter32_reg <= icmp_ln19_reg_268_pp0_iter31_reg;
        icmp_ln19_reg_268_pp0_iter33_reg <= icmp_ln19_reg_268_pp0_iter32_reg;
        icmp_ln19_reg_268_pp0_iter34_reg <= icmp_ln19_reg_268_pp0_iter33_reg;
        icmp_ln19_reg_268_pp0_iter35_reg <= icmp_ln19_reg_268_pp0_iter34_reg;
        icmp_ln19_reg_268_pp0_iter36_reg <= icmp_ln19_reg_268_pp0_iter35_reg;
        icmp_ln19_reg_268_pp0_iter37_reg <= icmp_ln19_reg_268_pp0_iter36_reg;
        icmp_ln19_reg_268_pp0_iter38_reg <= icmp_ln19_reg_268_pp0_iter37_reg;
        icmp_ln19_reg_268_pp0_iter39_reg <= icmp_ln19_reg_268_pp0_iter38_reg;
        icmp_ln19_reg_268_pp0_iter3_reg <= icmp_ln19_reg_268_pp0_iter2_reg;
        icmp_ln19_reg_268_pp0_iter40_reg <= icmp_ln19_reg_268_pp0_iter39_reg;
        icmp_ln19_reg_268_pp0_iter4_reg <= icmp_ln19_reg_268_pp0_iter3_reg;
        icmp_ln19_reg_268_pp0_iter5_reg <= icmp_ln19_reg_268_pp0_iter4_reg;
        icmp_ln19_reg_268_pp0_iter6_reg <= icmp_ln19_reg_268_pp0_iter5_reg;
        icmp_ln19_reg_268_pp0_iter7_reg <= icmp_ln19_reg_268_pp0_iter6_reg;
        icmp_ln19_reg_268_pp0_iter8_reg <= icmp_ln19_reg_268_pp0_iter7_reg;
        icmp_ln19_reg_268_pp0_iter9_reg <= icmp_ln19_reg_268_pp0_iter8_reg;
        mul3_reg_327 <= grp_fu_147_p_dout0;
        p_x_assign_1_reg_292 <= grp_fu_150_p2;
        p_x_assign_reg_287 <= grp_fu_146_p2;
        storereflowmerge_reg_337 <= grp_fu_138_p_dout0;
        sub_reg_317 <= grp_fu_134_p_dout0;
        tmp_reg_302 <= grp_sin_or_cos_float_s_fu_116_ap_return;
        tmp_s_reg_307 <= grp_sin_or_cos_float_s_fu_129_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter9_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter10_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter11_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter12_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter13_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter15_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter14_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter15 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter16_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter15_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter17_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter16_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter17 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter18_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter17_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter18 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter19_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter18_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter20_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter19_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter21_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter20_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter21 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter22_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter21_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter22 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter23_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter22_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter23 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter24_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter23_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter24 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter25_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter24_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter25 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter26_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter25_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter27_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter26_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        ap_phi_reg_pp0_iter28_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter27_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter28 == 1'b1))) begin
        ap_phi_reg_pp0_iter29_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter28_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter1_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter29 == 1'b1))) begin
        ap_phi_reg_pp0_iter30_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter29_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        ap_phi_reg_pp0_iter31_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter30_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
        ap_phi_reg_pp0_iter32_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter31_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        ap_phi_reg_pp0_iter33_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter32_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter33 == 1'b1))) begin
        ap_phi_reg_pp0_iter34_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter33_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        ap_phi_reg_pp0_iter35_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter34_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        ap_phi_reg_pp0_iter36_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter35_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        ap_phi_reg_pp0_iter37_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter36_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        ap_phi_reg_pp0_iter38_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter37_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter38 == 1'b1))) begin
        ap_phi_reg_pp0_iter39_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter38_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter2_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        ap_phi_reg_pp0_iter40_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter39_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter40 == 1'b1))) begin
        ap_phi_reg_pp0_iter41_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter40_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter4_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter3_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter4_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter5_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter6_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter7_storereflowmerge_in_reg_106;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_storereflowmerge_in_reg_106 <= ap_phi_reg_pp0_iter8_storereflowmerge_in_reg_106;
    end
end

always @ (*) begin
    if (((icmp_ln16_fu_211_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter44_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_idle_pp0 == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) 
    & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i1_load = 5'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_142_ce = 1'b1;
    end else begin
        grp_fu_142_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_146_ce = 1'b1;
    end else begin
        grp_fu_146_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_150_ce = 1'b1;
    end else begin
        grp_fu_150_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_154_ce = 1'b1;
    end else begin
        grp_fu_154_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_157_ce = 1'b1;
    end else begin
        grp_fu_157_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_161_ce = 1'b1;
    end else begin
        grp_fu_161_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_164_ce = 1'b1;
    end else begin
        grp_fu_164_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_169_ce = 1'b1;
    end else begin
        grp_fu_169_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_173_ce = 1'b1;
    end else begin
        grp_fu_173_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp76) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_sin_or_cos_float_s_fu_116_ap_ce = 1'b1;
    end else begin
        grp_sin_or_cos_float_s_fu_116_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp77) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_sin_or_cos_float_s_fu_129_ap_ce = 1'b1;
    end else begin
        grp_sin_or_cos_float_s_fu_129_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter44 == 1'b1))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_fu_188_p2 = ($signed(ap_sig_allocacmp_i1_load) + $signed(5'd20));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp76 = ((m_axi_gmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp77 = ((m_axi_gmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b1));
end

assign ap_block_pp0_stage0_ignoreCallOp76 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp77 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem_WREADY == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b1));
end

always @ (*) begin
    ap_condition_555 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storereflowmerge_in_reg_106 = 'bx;

assign ap_ready = ap_ready_sig;

assign grp_fu_134_p_ce = grp_fu_142_ce;

assign grp_fu_134_p_din0 = tmp_reg_302;

assign grp_fu_134_p_din1 = tmp_s_reg_307;

assign grp_fu_134_p_opcode = 2'd1;

assign grp_fu_138_p_ce = grp_fu_157_ce;

assign grp_fu_138_p_din0 = ap_phi_reg_pp0_iter42_storereflowmerge_in_reg_106;

assign grp_fu_144_p_ce = grp_fu_161_ce;

assign grp_fu_144_p_din0 = sub_reg_317;

assign grp_fu_147_p_ce = grp_fu_164_ce;

assign grp_fu_147_p_din0 = conv6_reg_312;

assign grp_fu_147_p_din1 = 64'd4614256656552045848;

assign grp_fu_154_p0 = add_ln19_fu_188_p2;

assign grp_fu_157_p_ce = grp_fu_169_ce;

assign grp_fu_157_p_din0 = conv5_reg_322;

assign grp_fu_157_p_din1 = mul3_reg_327;

assign grp_fu_173_p0 = add_ln19_reg_263_pp0_iter10_reg;

assign i_fu_200_p2 = (ap_sig_allocacmp_i1_load + 5'd1);

assign icmp_ln16_fu_211_p2 = ((ap_sig_allocacmp_i1_load == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_194_p2 = ((add_ln19_fu_188_p2 == 5'd0) ? 1'b1 : 1'b0);

assign m_axi_gmem_ARADDR = 64'd0;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd0;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_ARVALID = 1'b0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_RREADY = 1'b0;

assign m_axi_gmem_WDATA = storereflowmerge_reg_337;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 4'd15;

assign m_axi_gmem_WUSER = 1'd0;

endmodule //calculateCoefficients_calculateCoefficients_Pipeline_VITIS_LOOP_16_1
