-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hilbert_envelope_axis is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_stream_TVALID : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (4 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (5 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (4 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (5 downto 0) );
end;


architecture behav of hilbert_envelope_axis is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hilbert_envelope_axis_hilbert_envelope_axis,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sfvc784-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.623625,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1540,HLS_SYN_LUT=2593,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv93_68DB8BAC710D : STD_LOGIC_VECTOR (92 downto 0) := "000000000000000000000000000000000000000000000011010001101101110001011101011000111000100001101";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv93_0 : STD_LOGIC_VECTOR (92 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_5C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011100";
    constant ap_const_lv46_0 : STD_LOGIC_VECTOR (45 downto 0) := "0000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv9_181 : STD_LOGIC_VECTOR (8 downto 0) := "110000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_last_fu_288_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZZL7hilbertiRiE1x_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_21 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_ZZL7hilbertiRiE1x_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal hilbert_int_int_x : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal tmp_keep_reg_1259 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_keep_reg_1259_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_keep_reg_1259_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter11_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter12_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter13_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_strb_reg_1264_pp0_iter14_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_user_reg_1269 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_user_reg_1269_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_last_reg_1274 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_reg_1274_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_reg_1279 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter9_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter10_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter11_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter12_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_id_reg_1279_pp0_iter14_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_dest_reg_1284 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter2_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter3_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter4_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter5_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter6_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter7_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter8_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter9_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter10_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter11_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter12_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter13_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_dest_reg_1284_pp0_iter14_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal I_path_reg_1289 : STD_LOGIC_VECTOR (31 downto 0);
    signal I_path_reg_1289_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln45_4_fu_1034_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln45_4_reg_1294 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_26_reg_1299 : STD_LOGIC_VECTOR (0 downto 0);
    signal Q_path_fu_1099_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal Q_path_reg_1305 : STD_LOGIC_VECTOR (45 downto 0);
    signal mul_ln47_fu_259_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_reg_1310 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_1_fu_263_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_1_reg_1315 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_251_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal x_assign_reg_1325 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_254_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dc_reg_1330 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal grp_fu_251_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_fu_259_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln47_fu_1111_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_fu_259_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln47_1_fu_263_p0 : STD_LOGIC_VECTOR (34 downto 0);
    signal sext_ln45_6_fu_1106_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal mul_ln47_1_fu_263_p1 : STD_LOGIC_VECTOR (34 downto 0);
    signal mul_ln45_fu_267_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sub_ln37_fu_540_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln38_fu_550_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln39_fu_560_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln40_fu_570_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_592_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_1_fu_604_p3 : STD_LOGIC_VECTOR (38 downto 0);
    signal sext_ln45_fu_600_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_1_fu_612_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_5_fu_622_p3 : STD_LOGIC_VECTOR (35 downto 0);
    signal sub_ln45_2_fu_616_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_7_fu_630_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_6_fu_640_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln45_5_fu_634_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_8_fu_648_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sub_ln45_3_fu_652_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln40_fu_566_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_7_fu_664_p3 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_8_fu_676_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln45_9_fu_672_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_10_fu_684_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_9_fu_694_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal add_ln45_7_fu_688_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_11_fu_702_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal add_ln45_8_fu_706_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln38_fu_546_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sub_ln45_4_fu_712_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sub_ln41_fu_580_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_722_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_11_fu_734_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sext_ln45_12_fu_730_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_13_fu_742_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_12_fu_752_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln45_9_fu_746_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_14_fu_760_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_13_fu_770_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln45_10_fu_764_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_15_fu_778_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_14_fu_788_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_15_fu_800_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln45_16_fu_796_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_17_fu_808_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_16_fu_818_p3 : STD_LOGIC_VECTOR (34 downto 0);
    signal add_ln45_12_fu_812_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_18_fu_826_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal sub_ln45_5_fu_830_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln41_fu_576_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal sub_ln42_fu_586_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_842_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_18_fu_854_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_19_fu_850_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_20_fu_862_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_19_fu_872_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal sub_ln45_6_fu_866_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_21_fu_880_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_20_fu_890_p3 : STD_LOGIC_VECTOR (36 downto 0);
    signal add_ln45_14_fu_884_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_22_fu_898_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_21_fu_908_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln45_7_fu_902_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_23_fu_916_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal tmp_22_fu_926_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_23_fu_938_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal sext_ln45_24_fu_934_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_25_fu_946_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_24_fu_956_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal sub_ln45_9_fu_950_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_26_fu_964_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_25_fu_974_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal sub_ln45_10_fu_968_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_27_fu_982_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal add_ln45_15_fu_986_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln39_fu_556_p1 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_2_fu_718_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln45_11_fu_782_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln45_fu_998_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_3_fu_1004_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal sub_ln45_8_fu_920_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln45_6_fu_658_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sub_ln45_11_fu_992_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal add_ln45_2_fu_1014_p2 : STD_LOGIC_VECTOR (42 downto 0);
    signal sext_ln45_4_fu_1020_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln45_13_fu_836_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal add_ln45_3_fu_1024_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln45_5_fu_1030_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal add_ln45_1_fu_1008_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal mul_ln45_fu_267_p2 : STD_LOGIC_VECTOR (92 downto 0);
    signal sub_ln45_fu_1052_p2 : STD_LOGIC_VECTOR (92 downto 0);
    signal tmp_28_fu_1068_p4 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_27_fu_1058_p4 : STD_LOGIC_VECTOR (32 downto 0);
    signal select_ln45_1_fu_1082_p3 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_ln45_30_fu_1089_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal sub_ln45_1_fu_1093_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal sext_ln45_29_fu_1078_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal data_fu_1121_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln342_fu_1142_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mantissa_fu_1146_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal xs_exp_fu_1132_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln317_fu_1160_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln317_fu_1164_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln18_fu_1178_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_1170_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln18_fu_1184_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln18_fu_1188_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln18_1_fu_1196_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln15_fu_1156_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal zext_ln18_fu_1200_p1 : STD_LOGIC_VECTOR (78 downto 0);
    signal lshr_ln18_fu_1204_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal shl_ln18_fu_1210_p2 : STD_LOGIC_VECTOR (78 downto 0);
    signal tmp_3_fu_1216_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_1226_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_1236_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal xs_sign_fu_1124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_1_fu_1244_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_251_ce : STD_LOGIC;
    signal grp_fu_254_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (4 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (5 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hilbert_envelope_axis_sitofp_64ns_32_4_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hilbert_envelope_axis_fsqrt_32ns_32ns_32_8_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component hilbert_envelope_axis_mul_32s_32s_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component hilbert_envelope_axis_mul_35s_35s_64_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (34 downto 0);
        din1 : IN STD_LOGIC_VECTOR (34 downto 0);
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component hilbert_envelope_axis_mul_46s_48ns_93_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (45 downto 0);
        din1 : IN STD_LOGIC_VECTOR (47 downto 0);
        dout : OUT STD_LOGIC_VECTOR (92 downto 0) );
    end component;


    component hilbert_envelope_axis_flow_control_loop_pipe_no_ap_cont IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component hilbert_envelope_axis_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    sitofp_64ns_32_4_no_dsp_1_U1 : component hilbert_envelope_axis_sitofp_64ns_32_4_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 64,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => grp_fu_251_p0,
        ce => grp_fu_251_ce,
        dout => grp_fu_251_p1);

    fsqrt_32ns_32ns_32_8_no_dsp_1_U2 : component hilbert_envelope_axis_fsqrt_32ns_32ns_32_8_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => ap_const_lv32_0,
        din1 => x_assign_reg_1325,
        ce => grp_fu_254_ce,
        dout => grp_fu_254_p2);

    mul_32s_32s_64_1_1_U3 : component hilbert_envelope_axis_mul_32s_32s_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        din0 => mul_ln47_fu_259_p0,
        din1 => mul_ln47_fu_259_p1,
        dout => mul_ln47_fu_259_p2);

    mul_35s_35s_64_1_1_U4 : component hilbert_envelope_axis_mul_35s_35s_64_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 35,
        din1_WIDTH => 35,
        dout_WIDTH => 64)
    port map (
        din0 => mul_ln47_1_fu_263_p0,
        din1 => mul_ln47_1_fu_263_p1,
        dout => mul_ln47_1_fu_263_p2);

    mul_46s_48ns_93_1_1_U5 : component hilbert_envelope_axis_mul_46s_48ns_93_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 46,
        din1_WIDTH => 48,
        dout_WIDTH => 93)
    port map (
        din0 => add_ln45_4_reg_1294,
        din1 => mul_ln45_fu_267_p1,
        dout => mul_ln45_fu_267_p2);

    flow_control_loop_pipe_no_ap_cont_U : component hilbert_envelope_axis_flow_control_loop_pipe_no_ap_cont
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_const_logic_1,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_const_logic_0,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_const_logic_0);

    regslice_both_in_stream_V_data_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_reg_1259_pp0_iter14_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_reg_1264_pp0_iter14_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_user_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_user_reg_1269_pp0_iter14_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_user_V_U_ack_in_dummy,
        data_out => out_stream_TUSER,
        vld_out => regslice_both_out_stream_V_user_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_user_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_reg_1274_pp0_iter14_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_id_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 5)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_id_reg_1279_pp0_iter14_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_id_V_U_ack_in_dummy,
        data_out => out_stream_TID,
        vld_out => regslice_both_out_stream_V_id_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_id_V_U_apdone_blk);

    regslice_both_out_stream_V_dest_V_U : component hilbert_envelope_axis_regslice_both
    generic map (
        DataWidth => 6)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_dest_reg_1284_pp0_iter14_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_dest_V_U_ack_in_dummy,
        data_out => out_stream_TDEST,
        vld_out => regslice_both_out_stream_V_dest_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                I_path_reg_1289 <= p_ZZL7hilbertiRiE1x_11;
                I_path_reg_1289_pp0_iter1_reg <= I_path_reg_1289;
                Q_path_reg_1305 <= Q_path_fu_1099_p3;
                add_ln45_4_reg_1294 <= add_ln45_4_fu_1034_p2;
                tmp_26_reg_1299 <= add_ln45_4_fu_1034_p2(45 downto 45);
                tmp_dest_reg_1284 <= in_stream_TDEST_int_regslice;
                tmp_dest_reg_1284_pp0_iter1_reg <= tmp_dest_reg_1284;
                tmp_id_reg_1279 <= in_stream_TID_int_regslice;
                tmp_id_reg_1279_pp0_iter1_reg <= tmp_id_reg_1279;
                tmp_keep_reg_1259 <= in_stream_TKEEP_int_regslice;
                tmp_keep_reg_1259_pp0_iter1_reg <= tmp_keep_reg_1259;
                tmp_last_reg_1274 <= in_stream_TLAST_int_regslice;
                tmp_last_reg_1274_pp0_iter1_reg <= tmp_last_reg_1274;
                tmp_strb_reg_1264 <= in_stream_TSTRB_int_regslice;
                tmp_strb_reg_1264_pp0_iter1_reg <= tmp_strb_reg_1264;
                tmp_user_reg_1269 <= in_stream_TUSER_int_regslice;
                tmp_user_reg_1269_pp0_iter1_reg <= tmp_user_reg_1269;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                dc_reg_1330 <= grp_fu_254_p2;
                mul_ln47_1_reg_1315 <= mul_ln47_1_fu_263_p2;
                mul_ln47_reg_1310 <= mul_ln47_fu_259_p2;
                tmp_dest_reg_1284_pp0_iter10_reg <= tmp_dest_reg_1284_pp0_iter9_reg;
                tmp_dest_reg_1284_pp0_iter11_reg <= tmp_dest_reg_1284_pp0_iter10_reg;
                tmp_dest_reg_1284_pp0_iter12_reg <= tmp_dest_reg_1284_pp0_iter11_reg;
                tmp_dest_reg_1284_pp0_iter13_reg <= tmp_dest_reg_1284_pp0_iter12_reg;
                tmp_dest_reg_1284_pp0_iter14_reg <= tmp_dest_reg_1284_pp0_iter13_reg;
                tmp_dest_reg_1284_pp0_iter2_reg <= tmp_dest_reg_1284_pp0_iter1_reg;
                tmp_dest_reg_1284_pp0_iter3_reg <= tmp_dest_reg_1284_pp0_iter2_reg;
                tmp_dest_reg_1284_pp0_iter4_reg <= tmp_dest_reg_1284_pp0_iter3_reg;
                tmp_dest_reg_1284_pp0_iter5_reg <= tmp_dest_reg_1284_pp0_iter4_reg;
                tmp_dest_reg_1284_pp0_iter6_reg <= tmp_dest_reg_1284_pp0_iter5_reg;
                tmp_dest_reg_1284_pp0_iter7_reg <= tmp_dest_reg_1284_pp0_iter6_reg;
                tmp_dest_reg_1284_pp0_iter8_reg <= tmp_dest_reg_1284_pp0_iter7_reg;
                tmp_dest_reg_1284_pp0_iter9_reg <= tmp_dest_reg_1284_pp0_iter8_reg;
                tmp_id_reg_1279_pp0_iter10_reg <= tmp_id_reg_1279_pp0_iter9_reg;
                tmp_id_reg_1279_pp0_iter11_reg <= tmp_id_reg_1279_pp0_iter10_reg;
                tmp_id_reg_1279_pp0_iter12_reg <= tmp_id_reg_1279_pp0_iter11_reg;
                tmp_id_reg_1279_pp0_iter13_reg <= tmp_id_reg_1279_pp0_iter12_reg;
                tmp_id_reg_1279_pp0_iter14_reg <= tmp_id_reg_1279_pp0_iter13_reg;
                tmp_id_reg_1279_pp0_iter2_reg <= tmp_id_reg_1279_pp0_iter1_reg;
                tmp_id_reg_1279_pp0_iter3_reg <= tmp_id_reg_1279_pp0_iter2_reg;
                tmp_id_reg_1279_pp0_iter4_reg <= tmp_id_reg_1279_pp0_iter3_reg;
                tmp_id_reg_1279_pp0_iter5_reg <= tmp_id_reg_1279_pp0_iter4_reg;
                tmp_id_reg_1279_pp0_iter6_reg <= tmp_id_reg_1279_pp0_iter5_reg;
                tmp_id_reg_1279_pp0_iter7_reg <= tmp_id_reg_1279_pp0_iter6_reg;
                tmp_id_reg_1279_pp0_iter8_reg <= tmp_id_reg_1279_pp0_iter7_reg;
                tmp_id_reg_1279_pp0_iter9_reg <= tmp_id_reg_1279_pp0_iter8_reg;
                tmp_keep_reg_1259_pp0_iter10_reg <= tmp_keep_reg_1259_pp0_iter9_reg;
                tmp_keep_reg_1259_pp0_iter11_reg <= tmp_keep_reg_1259_pp0_iter10_reg;
                tmp_keep_reg_1259_pp0_iter12_reg <= tmp_keep_reg_1259_pp0_iter11_reg;
                tmp_keep_reg_1259_pp0_iter13_reg <= tmp_keep_reg_1259_pp0_iter12_reg;
                tmp_keep_reg_1259_pp0_iter14_reg <= tmp_keep_reg_1259_pp0_iter13_reg;
                tmp_keep_reg_1259_pp0_iter2_reg <= tmp_keep_reg_1259_pp0_iter1_reg;
                tmp_keep_reg_1259_pp0_iter3_reg <= tmp_keep_reg_1259_pp0_iter2_reg;
                tmp_keep_reg_1259_pp0_iter4_reg <= tmp_keep_reg_1259_pp0_iter3_reg;
                tmp_keep_reg_1259_pp0_iter5_reg <= tmp_keep_reg_1259_pp0_iter4_reg;
                tmp_keep_reg_1259_pp0_iter6_reg <= tmp_keep_reg_1259_pp0_iter5_reg;
                tmp_keep_reg_1259_pp0_iter7_reg <= tmp_keep_reg_1259_pp0_iter6_reg;
                tmp_keep_reg_1259_pp0_iter8_reg <= tmp_keep_reg_1259_pp0_iter7_reg;
                tmp_keep_reg_1259_pp0_iter9_reg <= tmp_keep_reg_1259_pp0_iter8_reg;
                tmp_last_reg_1274_pp0_iter10_reg <= tmp_last_reg_1274_pp0_iter9_reg;
                tmp_last_reg_1274_pp0_iter11_reg <= tmp_last_reg_1274_pp0_iter10_reg;
                tmp_last_reg_1274_pp0_iter12_reg <= tmp_last_reg_1274_pp0_iter11_reg;
                tmp_last_reg_1274_pp0_iter13_reg <= tmp_last_reg_1274_pp0_iter12_reg;
                tmp_last_reg_1274_pp0_iter14_reg <= tmp_last_reg_1274_pp0_iter13_reg;
                tmp_last_reg_1274_pp0_iter2_reg <= tmp_last_reg_1274_pp0_iter1_reg;
                tmp_last_reg_1274_pp0_iter3_reg <= tmp_last_reg_1274_pp0_iter2_reg;
                tmp_last_reg_1274_pp0_iter4_reg <= tmp_last_reg_1274_pp0_iter3_reg;
                tmp_last_reg_1274_pp0_iter5_reg <= tmp_last_reg_1274_pp0_iter4_reg;
                tmp_last_reg_1274_pp0_iter6_reg <= tmp_last_reg_1274_pp0_iter5_reg;
                tmp_last_reg_1274_pp0_iter7_reg <= tmp_last_reg_1274_pp0_iter6_reg;
                tmp_last_reg_1274_pp0_iter8_reg <= tmp_last_reg_1274_pp0_iter7_reg;
                tmp_last_reg_1274_pp0_iter9_reg <= tmp_last_reg_1274_pp0_iter8_reg;
                tmp_strb_reg_1264_pp0_iter10_reg <= tmp_strb_reg_1264_pp0_iter9_reg;
                tmp_strb_reg_1264_pp0_iter11_reg <= tmp_strb_reg_1264_pp0_iter10_reg;
                tmp_strb_reg_1264_pp0_iter12_reg <= tmp_strb_reg_1264_pp0_iter11_reg;
                tmp_strb_reg_1264_pp0_iter13_reg <= tmp_strb_reg_1264_pp0_iter12_reg;
                tmp_strb_reg_1264_pp0_iter14_reg <= tmp_strb_reg_1264_pp0_iter13_reg;
                tmp_strb_reg_1264_pp0_iter2_reg <= tmp_strb_reg_1264_pp0_iter1_reg;
                tmp_strb_reg_1264_pp0_iter3_reg <= tmp_strb_reg_1264_pp0_iter2_reg;
                tmp_strb_reg_1264_pp0_iter4_reg <= tmp_strb_reg_1264_pp0_iter3_reg;
                tmp_strb_reg_1264_pp0_iter5_reg <= tmp_strb_reg_1264_pp0_iter4_reg;
                tmp_strb_reg_1264_pp0_iter6_reg <= tmp_strb_reg_1264_pp0_iter5_reg;
                tmp_strb_reg_1264_pp0_iter7_reg <= tmp_strb_reg_1264_pp0_iter6_reg;
                tmp_strb_reg_1264_pp0_iter8_reg <= tmp_strb_reg_1264_pp0_iter7_reg;
                tmp_strb_reg_1264_pp0_iter9_reg <= tmp_strb_reg_1264_pp0_iter8_reg;
                tmp_user_reg_1269_pp0_iter10_reg <= tmp_user_reg_1269_pp0_iter9_reg;
                tmp_user_reg_1269_pp0_iter11_reg <= tmp_user_reg_1269_pp0_iter10_reg;
                tmp_user_reg_1269_pp0_iter12_reg <= tmp_user_reg_1269_pp0_iter11_reg;
                tmp_user_reg_1269_pp0_iter13_reg <= tmp_user_reg_1269_pp0_iter12_reg;
                tmp_user_reg_1269_pp0_iter14_reg <= tmp_user_reg_1269_pp0_iter13_reg;
                tmp_user_reg_1269_pp0_iter2_reg <= tmp_user_reg_1269_pp0_iter1_reg;
                tmp_user_reg_1269_pp0_iter3_reg <= tmp_user_reg_1269_pp0_iter2_reg;
                tmp_user_reg_1269_pp0_iter4_reg <= tmp_user_reg_1269_pp0_iter3_reg;
                tmp_user_reg_1269_pp0_iter5_reg <= tmp_user_reg_1269_pp0_iter4_reg;
                tmp_user_reg_1269_pp0_iter6_reg <= tmp_user_reg_1269_pp0_iter5_reg;
                tmp_user_reg_1269_pp0_iter7_reg <= tmp_user_reg_1269_pp0_iter6_reg;
                tmp_user_reg_1269_pp0_iter8_reg <= tmp_user_reg_1269_pp0_iter7_reg;
                tmp_user_reg_1269_pp0_iter9_reg <= tmp_user_reg_1269_pp0_iter8_reg;
                x_assign_reg_1325 <= grp_fu_251_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                hilbert_int_int_x <= in_stream_TDATA_int_regslice;
                hilbert_int_int_x_1 <= hilbert_int_int_x;
                hilbert_int_int_x_2 <= hilbert_int_int_x_1;
                hilbert_int_int_x_3 <= hilbert_int_int_x_2;
                hilbert_int_int_x_4 <= hilbert_int_int_x_3;
                hilbert_int_int_x_5 <= hilbert_int_int_x_4;
                hilbert_int_int_x_6 <= hilbert_int_int_x_5;
                hilbert_int_int_x_7 <= hilbert_int_int_x_6;
                hilbert_int_int_x_8 <= hilbert_int_int_x_7;
                hilbert_int_int_x_9 <= hilbert_int_int_x_8;
                p_ZZL7hilbertiRiE1x_10 <= hilbert_int_int_x_9;
                p_ZZL7hilbertiRiE1x_11 <= p_ZZL7hilbertiRiE1x_10;
                p_ZZL7hilbertiRiE1x_12 <= p_ZZL7hilbertiRiE1x_11;
                p_ZZL7hilbertiRiE1x_13 <= p_ZZL7hilbertiRiE1x_12;
                p_ZZL7hilbertiRiE1x_14 <= p_ZZL7hilbertiRiE1x_13;
                p_ZZL7hilbertiRiE1x_15 <= p_ZZL7hilbertiRiE1x_14;
                p_ZZL7hilbertiRiE1x_16 <= p_ZZL7hilbertiRiE1x_15;
                p_ZZL7hilbertiRiE1x_17 <= p_ZZL7hilbertiRiE1x_16;
                p_ZZL7hilbertiRiE1x_18 <= p_ZZL7hilbertiRiE1x_17;
                p_ZZL7hilbertiRiE1x_19 <= p_ZZL7hilbertiRiE1x_18;
                p_ZZL7hilbertiRiE1x_20 <= p_ZZL7hilbertiRiE1x_19;
                p_ZZL7hilbertiRiE1x_21 <= p_ZZL7hilbertiRiE1x_20;
                p_ZZL7hilbertiRiE1x_22 <= p_ZZL7hilbertiRiE1x_21;
                p_ZZL7hilbertiRiE1x_23 <= p_ZZL7hilbertiRiE1x_22;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    Q_path_fu_1099_p3 <= 
        sub_ln45_1_fu_1093_p2 when (tmp_26_reg_1299(0) = '1') else 
        sext_ln45_29_fu_1078_p1;
    add_ln317_fu_1164_p2 <= std_logic_vector(unsigned(zext_ln317_fu_1160_p1) + unsigned(ap_const_lv9_181));
    add_ln45_10_fu_764_p2 <= std_logic_vector(unsigned(add_ln45_9_fu_746_p2) + unsigned(sext_ln45_14_fu_760_p1));
    add_ln45_11_fu_782_p2 <= std_logic_vector(unsigned(add_ln45_10_fu_764_p2) + unsigned(sext_ln45_15_fu_778_p1));
    add_ln45_12_fu_812_p2 <= std_logic_vector(signed(sext_ln45_16_fu_796_p1) + signed(sext_ln45_17_fu_808_p1));
    add_ln45_13_fu_836_p2 <= std_logic_vector(unsigned(sub_ln45_5_fu_830_p2) + unsigned(sext_ln41_fu_576_p1));
    add_ln45_14_fu_884_p2 <= std_logic_vector(unsigned(sub_ln45_6_fu_866_p2) + unsigned(sext_ln45_21_fu_880_p1));
    add_ln45_15_fu_986_p2 <= std_logic_vector(unsigned(sub_ln45_10_fu_968_p2) + unsigned(sext_ln45_27_fu_982_p1));
    add_ln45_1_fu_1008_p2 <= std_logic_vector(signed(sext_ln45_3_fu_1004_p1) + signed(sub_ln45_8_fu_920_p2));
    add_ln45_2_fu_1014_p2 <= std_logic_vector(unsigned(add_ln45_6_fu_658_p2) + unsigned(sub_ln45_11_fu_992_p2));
    add_ln45_3_fu_1024_p2 <= std_logic_vector(signed(sext_ln45_4_fu_1020_p1) + signed(add_ln45_13_fu_836_p2));
    add_ln45_4_fu_1034_p2 <= std_logic_vector(signed(sext_ln45_5_fu_1030_p1) + signed(add_ln45_1_fu_1008_p2));
    add_ln45_5_fu_634_p2 <= std_logic_vector(unsigned(sub_ln45_2_fu_616_p2) + unsigned(sext_ln45_7_fu_630_p1));
    add_ln45_6_fu_658_p2 <= std_logic_vector(unsigned(sub_ln45_3_fu_652_p2) + unsigned(sext_ln40_fu_566_p1));
    add_ln45_7_fu_688_p2 <= std_logic_vector(signed(sext_ln45_9_fu_672_p1) + signed(sext_ln45_10_fu_684_p1));
    add_ln45_8_fu_706_p2 <= std_logic_vector(unsigned(add_ln45_7_fu_688_p2) + unsigned(sext_ln45_11_fu_702_p1));
    add_ln45_9_fu_746_p2 <= std_logic_vector(signed(sext_ln45_12_fu_730_p1) + signed(sext_ln45_13_fu_742_p1));
    add_ln45_fu_998_p2 <= std_logic_vector(signed(sext_ln45_2_fu_718_p1) + signed(add_ln45_11_fu_782_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_block_state16_pp0_stage0_iter15, ap_enable_reg_pp0_iter15, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state17_pp0_stage0_iter16, ap_enable_reg_pp0_iter16, ap_loop_exit_ready_pp0_iter16_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state17_pp0_stage0_iter16) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state16_pp0_stage0_iter15) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_block_state16_pp0_stage0_iter15, ap_enable_reg_pp0_iter15, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state17_pp0_stage0_iter16, ap_enable_reg_pp0_iter16, ap_loop_exit_ready_pp0_iter16_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state17_pp0_stage0_iter16) or (out_stream_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state16_pp0_stage0_iter15) or (out_stream_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_state1_pp0_stage0_iter0, ap_block_state16_pp0_stage0_iter15, ap_enable_reg_pp0_iter15, regslice_both_out_stream_V_data_V_U_apdone_blk, ap_block_state17_pp0_stage0_iter16, ap_enable_reg_pp0_iter16, ap_loop_exit_ready_pp0_iter16_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state17_pp0_stage0_iter16) or (out_stream_TREADY_int_regslice = ap_const_logic_0))) or ((ap_enable_reg_pp0_iter15 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state16_pp0_stage0_iter15) or (out_stream_TREADY_int_regslice = ap_const_logic_0))) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_const_logic_1)));
    end process;


    ap_block_state16_pp0_stage0_iter15_assign_proc : process(out_stream_TREADY_int_regslice)
    begin
                ap_block_state16_pp0_stage0_iter15 <= (out_stream_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state17_pp0_stage0_iter16_assign_proc : process(regslice_both_out_stream_V_data_V_U_apdone_blk, out_stream_TREADY_int_regslice)
    begin
                ap_block_state17_pp0_stage0_iter16 <= ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or (out_stream_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(in_stream_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (in_stream_TVALID_int_regslice = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, tmp_last_fu_288_p1)
    begin
        if (((tmp_last_fu_288_p1 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready_pp0_iter16_reg <= ap_const_logic_0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    data_fu_1121_p1 <= dc_reg_1330;

    grp_fu_251_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_251_ce <= ap_const_logic_1;
        else 
            grp_fu_251_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_251_p0 <= std_logic_vector(unsigned(mul_ln47_1_reg_1315) + unsigned(mul_ln47_reg_1310));

    grp_fu_254_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_254_ce <= ap_const_logic_1;
        else 
            grp_fu_254_ce <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, in_stream_TVALID_int_regslice)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_TVALID_int_regslice;
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln18_fu_1204_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_1156_p1),to_integer(unsigned('0' & zext_ln18_fu_1200_p1(31-1 downto 0)))));
    mantissa_fu_1146_p4 <= ((ap_const_lv1_1 & trunc_ln342_fu_1142_p1) & ap_const_lv1_0);
    mul_ln45_fu_267_p1 <= ap_const_lv93_68DB8BAC710D(48 - 1 downto 0);
    mul_ln47_1_fu_263_p0 <= sext_ln45_6_fu_1106_p1(35 - 1 downto 0);
    mul_ln47_1_fu_263_p1 <= sext_ln45_6_fu_1106_p1(35 - 1 downto 0);
    mul_ln47_fu_259_p0 <= sext_ln47_fu_1111_p1(32 - 1 downto 0);
    mul_ln47_fu_259_p1 <= sext_ln47_fu_1111_p1(32 - 1 downto 0);

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_block_pp0_stage0, out_stream_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= 
        result_1_fu_1244_p2 when (xs_sign_fu_1124_p3(0) = '1') else 
        val_fu_1236_p3;
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter15, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    result_1_fu_1244_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(val_fu_1236_p3));
    select_ln18_fu_1188_p3 <= 
        sext_ln18_fu_1184_p1 when (tmp_30_fu_1170_p3(0) = '1') else 
        add_ln317_fu_1164_p2;
    select_ln45_1_fu_1082_p3 <= 
        tmp_27_fu_1058_p4 when (tmp_26_reg_1299(0) = '1') else 
        tmp_28_fu_1068_p4;
        sext_ln18_1_fu_1196_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln18_fu_1188_p3),32));

        sext_ln18_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln18_fu_1178_p2),9));

        sext_ln38_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln37_fu_540_p2),43));

        sext_ln39_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln38_fu_550_p2),43));

        sext_ln40_fu_566_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln39_fu_560_p2),43));

        sext_ln41_fu_576_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln40_fu_570_p2),44));

        sext_ln45_10_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_676_p3),43));

        sext_ln45_11_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_9_fu_694_p3),43));

        sext_ln45_12_fu_730_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_722_p3),44));

        sext_ln45_13_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_11_fu_734_p3),44));

        sext_ln45_14_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_12_fu_752_p3),44));

        sext_ln45_15_fu_778_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_13_fu_770_p3),44));

        sext_ln45_16_fu_796_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_fu_788_p3),44));

        sext_ln45_17_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_15_fu_800_p3),44));

        sext_ln45_18_fu_826_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_818_p3),44));

        sext_ln45_19_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_842_p3),46));

        sext_ln45_1_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_604_p3),43));

        sext_ln45_20_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_854_p3),46));

        sext_ln45_21_fu_880_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_19_fu_872_p3),46));

        sext_ln45_22_fu_898_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_890_p3),46));

        sext_ln45_23_fu_916_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_21_fu_908_p3),46));

        sext_ln45_24_fu_934_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_fu_926_p3),43));

        sext_ln45_25_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_23_fu_938_p3),43));

        sext_ln45_26_fu_964_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_24_fu_956_p3),43));

        sext_ln45_27_fu_982_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_25_fu_974_p3),43));

        sext_ln45_29_fu_1078_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_fu_1068_p4),46));

        sext_ln45_2_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln45_4_fu_712_p2),44));

        sext_ln45_30_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln45_1_fu_1082_p3),46));

        sext_ln45_3_fu_1004_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_fu_998_p2),46));

        sext_ln45_4_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_2_fu_1014_p2),44));

        sext_ln45_5_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln45_3_fu_1024_p2),46));

        sext_ln45_6_fu_1106_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Q_path_reg_1305),64));

        sext_ln45_7_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_622_p3),43));

        sext_ln45_8_fu_648_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_6_fu_640_p3),43));

        sext_ln45_9_fu_672_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_664_p3),43));

        sext_ln45_fu_600_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_592_p3),43));

        sext_ln47_fu_1111_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(I_path_reg_1289_pp0_iter1_reg),64));

    shl_ln18_fu_1210_p2 <= std_logic_vector(shift_left(unsigned(zext_ln15_fu_1156_p1),to_integer(unsigned('0' & zext_ln18_fu_1200_p1(31-1 downto 0)))));
    sub_ln18_fu_1178_p2 <= std_logic_vector(unsigned(ap_const_lv8_7F) - unsigned(xs_exp_fu_1132_p4));
    sub_ln37_fu_540_p2 <= std_logic_vector(unsigned(p_ZZL7hilbertiRiE1x_23) - unsigned(in_stream_TDATA_int_regslice));
    sub_ln38_fu_550_p2 <= std_logic_vector(unsigned(p_ZZL7hilbertiRiE1x_21) - unsigned(hilbert_int_int_x_1));
    sub_ln39_fu_560_p2 <= std_logic_vector(unsigned(p_ZZL7hilbertiRiE1x_19) - unsigned(hilbert_int_int_x_3));
    sub_ln40_fu_570_p2 <= std_logic_vector(unsigned(p_ZZL7hilbertiRiE1x_17) - unsigned(hilbert_int_int_x_5));
    sub_ln41_fu_580_p2 <= std_logic_vector(unsigned(p_ZZL7hilbertiRiE1x_15) - unsigned(hilbert_int_int_x_7));
    sub_ln42_fu_586_p2 <= std_logic_vector(unsigned(p_ZZL7hilbertiRiE1x_13) - unsigned(hilbert_int_int_x_9));
    sub_ln45_10_fu_968_p2 <= std_logic_vector(unsigned(sub_ln45_9_fu_950_p2) - unsigned(sext_ln45_26_fu_964_p1));
    sub_ln45_11_fu_992_p2 <= std_logic_vector(unsigned(add_ln45_15_fu_986_p2) - unsigned(sext_ln39_fu_556_p1));
    sub_ln45_1_fu_1093_p2 <= std_logic_vector(unsigned(ap_const_lv46_0) - unsigned(sext_ln45_30_fu_1089_p1));
    sub_ln45_2_fu_616_p2 <= std_logic_vector(signed(sext_ln45_fu_600_p1) - signed(sext_ln45_1_fu_612_p1));
    sub_ln45_3_fu_652_p2 <= std_logic_vector(unsigned(add_ln45_5_fu_634_p2) - unsigned(sext_ln45_8_fu_648_p1));
    sub_ln45_4_fu_712_p2 <= std_logic_vector(unsigned(add_ln45_8_fu_706_p2) - unsigned(sext_ln38_fu_546_p1));
    sub_ln45_5_fu_830_p2 <= std_logic_vector(unsigned(add_ln45_12_fu_812_p2) - unsigned(sext_ln45_18_fu_826_p1));
    sub_ln45_6_fu_866_p2 <= std_logic_vector(signed(sext_ln45_19_fu_850_p1) - signed(sext_ln45_20_fu_862_p1));
    sub_ln45_7_fu_902_p2 <= std_logic_vector(unsigned(add_ln45_14_fu_884_p2) - unsigned(sext_ln45_22_fu_898_p1));
    sub_ln45_8_fu_920_p2 <= std_logic_vector(unsigned(sub_ln45_7_fu_902_p2) - unsigned(sext_ln45_23_fu_916_p1));
    sub_ln45_9_fu_950_p2 <= std_logic_vector(signed(sext_ln45_24_fu_934_p1) - signed(sext_ln45_25_fu_946_p1));
    sub_ln45_fu_1052_p2 <= std_logic_vector(unsigned(ap_const_lv93_0) - unsigned(mul_ln45_fu_267_p2));
    tmp_10_fu_722_p3 <= (sub_ln41_fu_580_p2 & ap_const_lv11_0);
    tmp_11_fu_734_p3 <= (sub_ln41_fu_580_p2 & ap_const_lv6_0);
    tmp_12_fu_752_p3 <= (sub_ln41_fu_580_p2 & ap_const_lv3_0);
    tmp_13_fu_770_p3 <= (sub_ln41_fu_580_p2 & ap_const_lv1_0);
    tmp_14_fu_788_p3 <= (sub_ln40_fu_570_p2 & ap_const_lv10_0);
    tmp_15_fu_800_p3 <= (sub_ln40_fu_570_p2 & ap_const_lv8_0);
    tmp_16_fu_818_p3 <= (sub_ln40_fu_570_p2 & ap_const_lv3_0);
    tmp_17_fu_842_p3 <= (sub_ln42_fu_586_p2 & ap_const_lv13_0);
    tmp_18_fu_854_p3 <= (sub_ln42_fu_586_p2 & ap_const_lv11_0);
    tmp_19_fu_872_p3 <= (sub_ln42_fu_586_p2 & ap_const_lv8_0);
    tmp_1_fu_604_p3 <= (sub_ln39_fu_560_p2 & ap_const_lv7_0);
    tmp_20_fu_890_p3 <= (sub_ln42_fu_586_p2 & ap_const_lv5_0);
    tmp_21_fu_908_p3 <= (sub_ln42_fu_586_p2 & ap_const_lv1_0);
    tmp_22_fu_926_p3 <= (sub_ln38_fu_550_p2 & ap_const_lv10_0);
    tmp_23_fu_938_p3 <= (sub_ln38_fu_550_p2 & ap_const_lv8_0);
    tmp_24_fu_956_p3 <= (sub_ln38_fu_550_p2 & ap_const_lv6_0);
    tmp_25_fu_974_p3 <= (sub_ln38_fu_550_p2 & ap_const_lv2_0);
    tmp_27_fu_1058_p4 <= sub_ln45_fu_1052_p2(92 downto 60);
    tmp_28_fu_1068_p4 <= mul_ln45_fu_267_p2(92 downto 60);
    tmp_30_fu_1170_p3 <= add_ln317_fu_1164_p2(8 downto 8);
    tmp_3_fu_1216_p4 <= lshr_ln18_fu_1204_p2(55 downto 24);
    tmp_4_fu_1226_p4 <= shl_ln18_fu_1210_p2(55 downto 24);
    tmp_5_fu_622_p3 <= (sub_ln39_fu_560_p2 & ap_const_lv4_0);
    tmp_6_fu_640_p3 <= (sub_ln39_fu_560_p2 & ap_const_lv2_0);
    tmp_7_fu_664_p3 <= (sub_ln37_fu_540_p2 & ap_const_lv9_0);
    tmp_8_fu_676_p3 <= (sub_ln37_fu_540_p2 & ap_const_lv6_0);
    tmp_9_fu_694_p3 <= (sub_ln37_fu_540_p2 & ap_const_lv2_0);
    tmp_fu_592_p3 <= (sub_ln39_fu_560_p2 & ap_const_lv10_0);
    tmp_last_fu_288_p1 <= in_stream_TLAST_int_regslice;
    trunc_ln342_fu_1142_p1 <= data_fu_1121_p1(23 - 1 downto 0);
    val_fu_1236_p3 <= 
        tmp_3_fu_1216_p4 when (tmp_30_fu_1170_p3(0) = '1') else 
        tmp_4_fu_1226_p4;
    xs_exp_fu_1132_p4 <= data_fu_1121_p1(30 downto 23);
    xs_sign_fu_1124_p3 <= data_fu_1121_p1(31 downto 31);
    zext_ln15_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mantissa_fu_1146_p4),79));
    zext_ln18_fu_1200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln18_1_fu_1196_p1),79));
    zext_ln317_fu_1160_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xs_exp_fu_1132_p4),9));
end behav;
