---
MainSourceFile:  'C:/Temp/mlangweil/Motor-Simulator/HLS/Audio-Filtering/Audio-Filtering/hls/.autopilot/db/Config.pp.0.cpp'
Diagnostics:     
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_1223_1:  '
    FileOffset:      1223
    FilePath:        'C:\Xilinx\Vitis_HLS\2024.1\common\technology\autopilot\etc\ap_int_base.h'
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          802752
        Length:          0
        ReplacementText: 'VITIS_LOOP_1223_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_676_1:  '
    FileOffset:      676
    FilePath:        'C:\Xilinx\Vitis_HLS\2024.1\common\technology\autopilot\etc\ap_int_ref.h'
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1030117
        Length:          0
        ReplacementText: 'VITIS_LOOP_676_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_690_1:  '
    FileOffset:      690
    FilePath:        'C:\Xilinx\Vitis_HLS\2024.1\common\technology\autopilot\etc\ap_int_ref.h'
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1030581
        Length:          0
        ReplacementText: 'VITIS_LOOP_690_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_704_1:  '
    FileOffset:      704
    FilePath:        'C:\Xilinx\Vitis_HLS\2024.1\common\technology\autopilot\etc\ap_int_ref.h'
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1031046
        Length:          0
        ReplacementText: 'VITIS_LOOP_704_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_1247_1:  '
    FileOffset:      1247
    FilePath:        'C:\Xilinx\Vitis_HLS\2024.1\common\technology\autopilot\etc\ap_fixed_base.h'
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1314361
        Length:          0
        ReplacementText: 'VITIS_LOOP_1247_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_19_1:  '
    FileOffset:      19
    FilePath:        Config.cpp
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1753047
        Length:          0
        ReplacementText: 'VITIS_LOOP_19_1: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_23_2:  '
    FileOffset:      23
    FilePath:        Config.cpp
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1753238
        Length:          0
        ReplacementText: 'VITIS_LOOP_23_2: '
  - DiagnosticName:  xilinx-label-all-loops
    Message:         'Added loop label VITIS_LOOP_24_3:  '
    FileOffset:      24
    FilePath:        Config.cpp
    Replacements:    
      - FilePath:        'C:\Temp\mlangweil\Motor-Simulator\HLS\Audio-Filtering\Audio-Filtering\hls\.autopilot\db\Config.pp.0.cpp'
        Offset:          1753254
        Length:          0
        ReplacementText: 'VITIS_LOOP_24_3: '
...
